"use client";
import { useState } from "react";
import { content, routes, type Locale, type Route } from "../../../lib/content";

const Arrow = () => <span aria-hidden="true">→</span>;
const picture = (src: string) => ({ backgroundImage: `url('${src}')` });

export default function Page({ params }: { params: { locale: string; slug?: string[] } }) {
  const locale: Locale = params.locale === "ar" ? "ar" : "en";
  const page = (routes.find((x) => x === params.slug?.[0]) ?? "home") as Route | "home";
  const t = content[locale]; const ar = locale === "ar"; const [menu, setMenu] = useState(false);
  const href = (p: Route | "home", l = locale) => p === "home" ? `/${l}` : `/${l}/${p}`;
  return <div dir={ar ? "rtl" : "ltr"} className={ar ? "font-arabic" : ""}>
    <header className="absolute inset-x-0 top-0 z-30"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8 lg:px-10"><a href={href("home")} className="flex items-center gap-3 text-white"><span className="grid h-11 w-11 place-items-center rounded-xl border border-white/30 bg-white/10 font-[Outfit] font-extrabold backdrop-blur">AD</span><span><b className="block font-[Outfit] text-lg leading-none">{t.brand}</b><small className="text-[9px] font-bold tracking-wider text-sky">{t.subtitle}</small></span></a><nav className="hidden gap-5 text-sm font-semibold text-white/85 xl:flex">{routes.map(p => <a href={href(p)} className="hover:text-sky" key={p}>{t.nav[p]}</a>)}</nav><div className="hidden gap-3 sm:flex"><a href={href(page, ar ? "en" : "ar")} className="rounded-full border border-white/30 px-3 py-2 text-xs font-bold text-white">{ar ? "EN" : "العربية"}</a><a href={href("contact")} className="rounded-full bg-sky px-4 py-2 text-sm font-bold text-brand">{t.nav.contact}</a></div><button className="rounded-lg border border-white/30 px-3 py-2 text-sm text-white sm:hidden" onClick={() => setMenu(!menu)}>☰</button>{menu && <div className="absolute start-5 end-5 top-20 rounded-2xl bg-white p-5 text-brand shadow-xl sm:hidden">{(["home", ...routes] as const).map(p => <a className="block border-b border-slate-100 py-3 font-semibold" onClick={() => setMenu(false)} href={href(p)} key={p}>{t.nav[p]}</a>)}</div>}</div></header>
    {page === "home" ? <Home t={t} href={href} /> : <Inside page={page} t={t} />}
    <Footer t={t} href={href} />
  </div>;
}

function Home({ t, href }: { t: typeof content.en; href: (p: Route | "home", l?: Locale) => string }) { return <>
  <section className="relative flex min-h-screen items-end overflow-hidden bg-brand px-5 pb-16 pt-36 text-white sm:px-8 lg:px-10"><div className="absolute inset-0 bg-cover bg-center" style={picture("https://images.unsplash.com/photo-1581092160607-ee22621dd758?auto=format&fit=crop&w=1800&q=90")} /><div className="absolute inset-0 bg-gradient-to-r from-[#082643]/95 via-[#103a67]/82 to-[#103a67]/35" /><div className="relative mx-auto w-full max-w-7xl"><p className="section-kicker text-sky">{t.hero.eyebrow}</p><h1 className="mt-5 max-w-4xl font-[Outfit] text-5xl font-semibold leading-[.95] sm:text-7xl lg:text-8xl">{t.hero.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">{t.hero.text}</p><div className="mt-9 flex flex-wrap gap-3"><a href={href("products")} className="rounded-full bg-sky px-6 py-3.5 text-sm font-bold text-brand">{t.hero.primary} <Arrow /></a><a href={href("contact")} className="rounded-full border border-white/30 px-6 py-3.5 text-sm font-bold">{t.hero.secondary}</a></div></div></section>
  <Section title={t.overview.title} text={t.overview.text} label="AL DAWLIA" /><Cards title={t.products.title} text={t.products.text} cards={t.products.items.slice(0,3)} dark /><Process t={t} /><Cards title={t.manufacturing.title} text={t.manufacturing.text} cards={t.manufacturing.items} /><Industries t={t} /><Why t={t} /><Stats t={t} /><Cta t={t} href={href("contact")} />
</>}

function Inside({ page, t }: { page: Route; t: typeof content.en }) { const info = t[page] as typeof t.products; return <><section className="relative overflow-hidden bg-brand px-5 pb-16 pt-36 text-white sm:px-8 lg:px-10"><div className="absolute inset-0 opacity-25 bg-[radial-gradient(circle_at_80%_30%,#69c8f2,transparent_24%)]" /><div className="relative mx-auto max-w-7xl"><p className="section-kicker text-sky">{t.nav[page]}</p><h1 className="mt-5 max-w-3xl font-[Outfit] text-5xl font-semibold leading-tight sm:text-6xl">{info.title}</h1><p className="mt-6 max-w-2xl text-lg leading-8 text-white/75">{info.text}</p></div></section>{page === "products" && <Cards title="" text="" cards={t.products.items} />}{page === "manufacturing" && <Cards title="" text="" cards={t.manufacturing.items} />}{page === "industries" && <Industries t={t} />}{page === "quality" && <Quality t={t} />}{page === "sustainability" && <Why t={t} sustainability />}{page === "export" && <Export t={t} />}{page === "about" && <><Section title={t.overview.title} text={t.overview.text} label="AL DAWLIA" /><Stats t={t} /><Why t={t} /></>}{page === "contact" && <Contact t={t} />}</> }

function Section({ title, text, label }: { title: string; text: string; label: string }) { return <section className="mx-auto grid max-w-7xl gap-8 px-5 py-20 sm:px-8 lg:grid-cols-[.7fr_1.3fr] lg:px-10"><p className="section-kicker">{label}</p><div><h2 className="font-[Outfit] text-4xl font-semibold leading-tight text-brand sm:text-5xl">{title}</h2><p className="mt-5 max-w-2xl text-lg leading-8 text-slate-600">{text}</p></div></section> }
function Cards({ title, text, cards, dark = false }: { title: string; text: string; cards: typeof content.en.products.items; dark?: boolean }) { return <section className={dark ? "bg-pale" : "bg-white"}><div className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10">{title && <div className="mb-10"><h2 className="font-[Outfit] text-4xl font-semibold text-brand sm:text-5xl">{title}</h2><p className="mt-4 max-w-2xl text-slate-600">{text}</p></div>}<div className="grid gap-5 md:grid-cols-3">{cards.map(c => <article className="group overflow-hidden rounded-2xl border border-blue-100 bg-white shadow-sm" key={c.title}><div className="h-48 bg-cover bg-center transition duration-500 group-hover:scale-[1.03]" style={picture(c.image)} /><div className="p-6"><h3 className="font-[Outfit] text-2xl font-semibold text-brand">{c.title}</h3><p className="mt-3 text-sm leading-6 text-slate-600">{c.text}</p></div></article>)}</div></div></section> }
function Process({ t }: { t: typeof content.en }) { const flow = [t.manufacturing.items[0].title, t.manufacturing.items[1].title, t.manufacturing.items[2].title, t.quality.title]; return <section className="bg-brand px-5 py-20 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="section-kicker text-sky">{t.nav.manufacturing}</p><h2 className="mt-4 font-[Outfit] text-4xl font-semibold sm:text-5xl">{t.manufacturing.title}</h2><div className="mt-10 grid gap-5 md:grid-cols-4">{flow.map((x,i) => <div className="border-t border-sky/40 pt-5" key={x}><span className="font-[Outfit] text-3xl text-sky">0{i+1}</span><p className="mt-8 font-semibold">{x}</p></div>)}</div></div></section> }
function Industries({ t }: { t: typeof content.en }) { return <section className="bg-pale px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><h2 className="max-w-3xl font-[Outfit] text-4xl font-semibold text-brand sm:text-5xl">{t.industries.title}</h2><div className="mt-10 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{t.industries.items.map((x,i) => <div className="rounded-xl border border-blue-100 bg-white p-5 font-semibold text-brand" key={x}><span className="me-3 text-sky">0{i+1}</span>{x}</div>)}</div></div></section> }
function Why({ t, sustainability = false }: { t: typeof content.en; sustainability?: boolean }) { const d = sustainability ? t.sustainability : t.why; const points = sustainability ? t.sustainability.points : t.why.points; return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-2 lg:px-10"><div><p className="section-kicker">{sustainability ? t.nav.sustainability : "AL DAWLIA"}</p><h2 className="mt-4 font-[Outfit] text-4xl font-semibold leading-tight text-brand sm:text-5xl">{d.title}</h2>{"text" in d && <p className="mt-5 text-lg leading-8 text-slate-600">{d.text}</p>}</div><div className="grid gap-3 self-end">{points.map((p,i) => <div className="rounded-xl bg-pale p-5 font-semibold text-brand" key={p}><span className="me-3 text-sky">✓</span>{p}</div>)}</div></section> }
function Quality({ t }: { t: typeof content.en }) { return <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-3">{t.quality.standards.map(x => <div className="rounded-2xl border-2 border-blue-100 p-8 text-center" key={x}><span className="text-3xl text-sky">✓</span><p className="mt-5 font-[Outfit] text-2xl font-semibold text-brand">{x}</p></div>)}</div></section> }
function Export({ t }: { t: typeof content.en }) { return <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-5 md:grid-cols-2">{t.export.regions.map((r,i) => <div className="rounded-2xl bg-pale p-8" key={r}><span className="font-[Outfit] text-4xl font-bold text-sky">0{i+1}</span><p className="mt-12 font-[Outfit] text-2xl font-semibold text-brand">{r}</p></div>)}</div></section> }
function Stats({ t }: { t: typeof content.en }) { return <section className="bg-brand px-5 py-16 text-white sm:px-8 lg:px-10"><div className="mx-auto grid max-w-7xl gap-6 sm:grid-cols-2 lg:grid-cols-4">{t.stats.map(([n,l]) => <div className="border-s border-sky/50 ps-5" key={l}><p className="font-[Outfit] text-4xl font-bold text-sky">{n}</p><p className="mt-1 text-sm text-white/75">{l}</p></div>)}</div></section> }
function Contact({ t }: { t: typeof content.en }) { return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1.2fr_.8fr] lg:px-10"><form className="grid gap-4">{t.contact.labels.map((x,i) => <label className="text-sm font-bold text-brand" key={x}>{x}{i === 3 ? <textarea className="mt-2 h-32 w-full rounded-xl border border-blue-200 p-3" /> : <input className="mt-2 w-full rounded-xl border border-blue-200 p-3" />}</label>)}<button className="w-fit rounded-full bg-brand px-6 py-3.5 text-sm font-bold text-white">{t.contact.send}</button></form><aside className="rounded-2xl bg-pale p-8"><p className="section-kicker">AL DAWLIA</p><p className="mt-6 text-xl leading-8 text-brand">{t.contact.address}</p><a className="mt-6 block font-semibold text-blue-700" href="mailto:info@aldawlia.com">info@aldawlia.com</a><a className="mt-2 block font-semibold text-blue-700" href="tel:+20550000000">+20 55 000 0000</a></aside></section> }
function Cta({ t, href }: { t: typeof content.en; href: string }) { return <section className="bg-sky px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap items-end justify-between gap-8"><div><p className="section-kicker text-brand">{t.nav.contact}</p><h2 className="mt-4 max-w-2xl font-[Outfit] text-4xl font-semibold text-brand sm:text-5xl">{t.contact.title}</h2></div><a href={href} className="rounded-full bg-brand px-6 py-3.5 text-sm font-bold text-white">{t.hero.secondary} <Arrow /></a></div></section> }
function Footer({ t, href }: { t: typeof content.en; href: (p: Route | "home", l?: Locale) => string }) { return <footer className="bg-[#082643] px-5 py-12 text-white sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-wrap justify-between gap-8"><div><p className="font-[Outfit] text-2xl font-bold">{t.brand}</p><p className="mt-2 text-sm text-white/55">{t.footer}</p></div><div className="flex flex-wrap gap-4 text-sm text-white/65">{routes.slice(0,5).map(x => <a href={href(x)} key={x}>{t.nav[x]}</a>)}</div></div><p className="mx-auto mt-10 max-w-7xl border-t border-white/15 pt-5 text-xs text-white/40">© 2026 AL DAWLIA FOR PLASTIC MATERIALS. All rights reserved.</p></footer> }
