"use client";

import { use } from "react";
import { content, images, routes, type Locale, type Route } from "../../../lib/content";
import { SiteHeader } from "../../../components/site-header";
import { SiteFooter } from "../../../components/site-footer";
import { SectionHeading } from "../../../components/section-heading";
import { ProductCard } from "../../../components/product-card";
import { ArrowIcon, CheckIcon, FactoryIcon, MailIcon, PhoneIcon, PinIcon } from "../../../components/icons";

type PageProps = { params: Promise<{ locale: string; slug?: string[] }> };
const bg = (image: string) => ({ backgroundImage: `url('${image}')` });

export default function Page({ params }: PageProps) {
  const resolved = use(params); const locale: Locale = resolved.locale === "ar" ? "ar" : "en";
  const candidate = resolved.slug?.[0] as Route | undefined;
  const page: Route | "home" = candidate && routes.includes(candidate) ? candidate : "home";
  const t = content[locale]; const href = (path: Route | "home", target = locale) => path === "home" ? `/${target}` : `/${target}/${path}`;
  return <div dir={locale === "ar" ? "rtl" : "ltr"} className={locale === "ar" ? "font-arabic" : ""}>
    <SiteHeader locale={locale} active={page} copy={t} href={href} />
    {page === "home" ? <Home t={t} href={href} /> : <Inner page={page} t={t} href={href} />}
    <SiteFooter copy={t} href={href} />
  </div>;
}

function Home({ t, href }: { t: typeof content.en; href: (p: Route | "home") => string }) { return <>
  <section className="relative isolate flex min-h-[730px] items-end overflow-hidden bg-brand px-5 pb-20 pt-36 text-white sm:px-8 lg:px-10">
    <div className="absolute inset-0 -z-20 bg-cover bg-center" style={bg(images.hero)} /><div className="absolute inset-0 -z-10 bg-[linear-gradient(90deg,rgba(7,34,59,.97)_0%,rgba(15,61,102,.88)_46%,rgba(15,61,102,.42)_100%)]" /><div className="hero-grid absolute inset-0 -z-10 opacity-50" />
    <div className="relative mx-auto w-full max-w-7xl"><p className="eyebrow text-orange">{t.hero.eyebrow}</p><h1 className="mt-5 max-w-4xl whitespace-pre-line text-5xl font-semibold leading-[.94] sm:text-7xl lg:text-[5.4rem]">{t.hero.title}</h1><p className="mt-7 max-w-xl text-lg leading-8 text-white/80">{t.hero.text}</p><div className="mt-9 flex flex-wrap gap-3"><a href={href("products")} className="button-primary">{t.hero.primary}<ArrowIcon /></a><a href={href("contact")} className="button-ghost">{t.hero.secondary}</a></div></div>
  </section>
  <About t={t} /><Products t={t} limit={3} href={href} /><Production t={t} /><Why t={t} /><Stats t={t} /><Gallery t={t} /><Contact t={t} />
</> }

function Inner({ page, t, href }: { page: Route; t: typeof content.en; href: (p: Route | "home") => string }) { const data = page === "production-lines" ? t.production : t[page]; return <>
  <section className="relative overflow-hidden bg-brand px-5 pb-16 pt-36 text-white sm:px-8 lg:px-10"><div className="absolute inset-0 hero-grid opacity-30" /><div className="absolute -right-20 top-8 h-72 w-72 rounded-full bg-orange/20 blur-3xl" /><div className="relative mx-auto max-w-7xl"><p className="eyebrow text-orange">AL DAWLIA / {t.nav[page]}</p><h1 className="mt-5 max-w-3xl text-5xl font-semibold leading-tight sm:text-6xl">{data.title}</h1><p className="mt-5 max-w-2xl text-lg leading-8 text-white/75">{data.text}</p></div></section>
  {page === "about" && <><About t={t} expanded /><Why t={t} /><Stats t={t} /></>}
  {page === "products" && <Products t={t} href={href} />}
  {page === "production-lines" && <Production t={t} expanded />}
  {page === "quality" && <Quality t={t} />}
  {page === "gallery" && <Gallery t={t} expanded />}
  {page === "contact" && <Contact t={t} />}
</> }

function About({ t, expanded = false }: { t: typeof content.en; expanded?: boolean }) { return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[.85fr_1.15fr] lg:py-28 lg:px-10"><div><p className="eyebrow">AL DAWLIA</p><div className="mt-7 h-1 w-16 bg-orange" /></div><div><SectionHeading title={t.about.title} /><p className="mt-6 max-w-2xl text-lg leading-8 text-slate-600">{t.about.text}</p>{expanded && <p className="mt-5 max-w-2xl leading-7 text-slate-500">Our manufacturing capability is built around disciplined processes, responsive collaboration, and a clear focus on value for every customer we serve.</p>}</div></section> }
function Products({ t, limit, href }: { t: typeof content.en; limit?: number; href: (p: Route | "home") => string }) { const list = limit ? t.products.items.slice(0, limit) : t.products.items; return <section className="bg-gray-50 px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="flex flex-wrap items-end justify-between gap-5"><div><p className="eyebrow">OUR PRODUCTS</p><SectionHeading title={t.products.title} className="mt-4 max-w-2xl" /><p className="mt-4 max-w-2xl leading-7 text-slate-600">{t.products.text}</p></div>{limit && <a href={href("products")} className="text-sm font-bold text-brand hover:text-orange">View all products →</a>}</div><div className="mt-10 grid gap-5 sm:grid-cols-2 lg:grid-cols-3">{list.map((product) => <ProductCard key={product.title} product={product} />)}</div></div></section> }
function Production({ t, expanded = false }: { t: typeof content.en; expanded?: boolean }) { return <section className="bg-brand px-5 py-20 text-white sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><p className="eyebrow text-orange">PRODUCTION LINES</p><SectionHeading title={t.production.title} light className="mt-4" /><p className="mt-5 leading-7 text-white/70">{t.production.text}</p></div><div className="mt-12 grid gap-px overflow-hidden rounded-2xl bg-white/15 md:grid-cols-5">{t.production.stages.map((stage, i) => <div className="group bg-brand p-6 transition hover:bg-white/5" key={stage}><span className="text-sm font-bold text-orange">0{i + 1}</span><FactoryIcon className="mt-10 h-8 w-8 text-white/80" /><p className="mt-5 font-semibold">{stage}</p></div>)}</div>{expanded && <div className="mt-10 grid gap-6 md:grid-cols-2"><div className="rounded-2xl bg-white/7 p-7"><p className="font-semibold text-orange">Capabilities</p><p className="mt-3 leading-7 text-white/70">Flexible specifications, dependable output, and careful converting help us support varied packaging requirements.</p></div><div className="rounded-2xl bg-white/7 p-7"><p className="font-semibold text-orange">Built for continuity</p><p className="mt-3 leading-7 text-white/70">A connected process allows practical lead times and consistent attention to the details that matter.</p></div></div>}</div></section> }
function Why({ t }: { t: typeof content.en }) { return <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><div><p className="eyebrow">WHY AL DAWLIA</p><SectionHeading title={t.why.title} className="mt-4" /></div><div className="grid gap-3 sm:grid-cols-2">{t.why.items.map((item, i) => <div className="flex items-center gap-4 rounded-xl border border-slate-100 bg-gray-50 p-5" key={item}><span className="grid h-9 w-9 shrink-0 place-items-center rounded-full bg-orange/10 text-sm font-bold text-orange">0{i + 1}</span><span className="font-semibold text-brand">{item}</span></div>)}</div></div></section> }
function Stats({ t }: { t: typeof content.en }) { return <section className="bg-orange px-5 py-14 sm:px-8 lg:px-10"><div className="mx-auto grid max-w-7xl gap-8 sm:grid-cols-2 lg:grid-cols-4">{t.stats.map(([number, label]) => <div className="border-l border-brand/20 pl-5 first:border-0 first:pl-0" key={label}><p className="text-4xl font-bold text-brand">{number}</p><p className="mt-1 font-medium text-brand/75">{label}</p></div>)}</div></section> }
function Quality({ t }: { t: typeof content.en }) { return <section className="mx-auto grid max-w-7xl gap-10 px-5 py-20 sm:px-8 lg:grid-cols-[1fr_.9fr] lg:px-10"><div className="overflow-hidden rounded-2xl bg-cover bg-center min-h-[340px]" style={bg(images.lab)} /><div className="self-center"><p className="eyebrow">OUR COMMITMENT</p><SectionHeading title={t.quality.title} className="mt-4" /><p className="mt-5 leading-7 text-slate-600">{t.quality.text}</p><div className="mt-7 space-y-4">{t.quality.checks.map((item) => <div className="flex items-center gap-3 font-semibold text-brand" key={item}><CheckIcon />{item}</div>)}</div></div></section> }
function Gallery({ t, expanded = false }: { t: typeof content.en; expanded?: boolean }) { const photos = [images.factory, images.rolls, images.line, images.warehouse, images.lab, images.logistics]; return <section className="bg-gray-50 px-5 py-20 sm:px-8 lg:px-10"><div className="mx-auto max-w-7xl"><p className="eyebrow">GALLERY</p><SectionHeading title={t.gallery.title} className="mt-4" /><p className="mt-4 max-w-xl leading-7 text-slate-600">{t.gallery.text}</p><div className={`mt-10 grid gap-4 ${expanded ? "md:grid-cols-3" : "md:grid-cols-4"}`}>{photos.slice(0, expanded ? 6 : 4).map((photo, i) => <div key={photo} className={`group relative min-h-56 overflow-hidden rounded-2xl bg-cover bg-center ${i === 0 ? "md:col-span-2 md:row-span-2 md:min-h-[470px]" : ""}`} style={bg(photo)}><div className="absolute inset-0 bg-brand/0 transition group-hover:bg-brand/25" /></div>)}</div></div></section> }
function Contact({ t }: { t: typeof content.en }) { const details = [{ label: "ADDRESS", value: t.contact.address, icon: <PinIcon className="h-5 w-5" /> }, { label: "PHONE", value: "+20 109 751 3375", href: "tel:+201097513375", icon: <PhoneIcon className="h-5 w-5" /> }, { label: "EMAIL", value: "info@aldawlia-plastic.com", href: "mailto:info@aldawlia-plastic.com", icon: <MailIcon className="h-5 w-5" /> }]; return <section className="mx-auto max-w-7xl px-5 py-20 sm:px-8 lg:py-28 lg:px-10"><div className="grid gap-10 lg:grid-cols-[.8fr_1.2fr]"><aside className="rounded-2xl bg-brand p-8 text-white sm:p-10"><p className="eyebrow text-orange">GET IN TOUCH</p><h2 className="mt-5 text-3xl font-semibold leading-tight">{t.contact.title}</h2><p className="mt-5 leading-7 text-white/70">{t.contact.text}</p><div className="mt-10 grid gap-3">{details.map((detail) => <div className="flex gap-4 rounded-xl bg-white/8 p-4" key={detail.label}><span className="mt-1 text-orange">{detail.icon}</span><div className="min-w-0"><span className="block text-[10px] font-bold tracking-[.16em] text-orange">{detail.label}</span>{detail.href ? <a className="mt-1 block break-words text-sm font-medium text-white hover:text-orange" href={detail.href}>{detail.value}</a> : <p className="mt-1 whitespace-pre-line text-sm leading-6 text-white/80">{detail.value}</p>}</div></div>)}</div></aside><form className="grid gap-5 rounded-2xl border border-slate-100 bg-white p-5 shadow-card sm:p-8" onSubmit={(e) => e.preventDefault()}>{t.contact.form.map((label, i) => <label className="text-sm font-bold text-brand" key={label}>{label}{i === 3 ? <textarea required className="form-field h-32" /> : <input required type={i === 1 ? "email" : "text"} className="form-field" />}</label>)}<button className="button-primary w-fit" type="submit">{t.contact.send}<ArrowIcon /></button></form></div></section> }
